# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#

version: 2
jobs:
  build:
    docker:
    # Use the same Docker base as the project
      - image: python:3.7-stretch

    working_directory: ~/kubernetes_ML_app

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            # Install hadolint
            # wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            #    chmod +x /bin/hadolint
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run lint!
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint
deploy:
    machinre:

    working_directory: ~/kubernetes_ML_app

    steps:
      - checkout
      - run:
          name: build docker and push
          command: |
            . venv/bin/activate
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t phalligan/kubernetes-ml-app:$TAG .
            docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
            docker tag "phalligan/kubernetes-ml-app:$TAG" "$halligan/kubernetes-ml-app:latest"
            docker push "phalligan/kubernetes-ml-app:$TAG" 
            docker push "$phalligan/kubernetes-ml-app:latest"
            
  